server:
  port: 1905

spring:
  application:
    name: "payment-service"
  config:
    import: "optional:configserver:http://localhost:1907"

management:
  endpoints:
    web:
      exposure:
        include: "*"
